name: Build & deploy Node.js app to Azure Web App - dutchbrat-website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean
        run: |
          rm -rf frontend/.next deploy

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 1️⃣ Build Frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # 2️⃣ Build Backend
      - name: Install server dependencies
        working-directory: server
        run: npm install
      - name: Build server
        working-directory: server
        run: npm run build

      # 3️⃣ Package deploy folder
      - name: Prepare deploy folder
        run: |
          mkdir -p deploy

          # Copy Next.js build output, app/, and public/
          cp -r frontend/.next frontend/app frontend/public deploy/

          # Copy compiled server output into deploy/dist
          mkdir -p deploy/dist
          cp -r server/dist/* deploy/dist/

          # Copy root package.json so npm install can run
          cp package.json deploy/

          # Debug: list contents
          ls -R deploy

      # 4️⃣ Upload artifact
      - name: Upload deploy folder
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AZURE_RESOURCE_GROUP: YourResourceGroupName
      AZURE_APP_NAME: dutchbrat-website
      ZIP_PATH: deploy.zip

    steps:
      - name: Download deploy folder
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Create zip package
        run: |
          cd deploy
          zip -r ../${{ env.ZIP_PATH }} .
          cd ..

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy via Azure CLI (run-from-package)
        run: |
          az webapp deploy \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_APP_NAME }} \
            --src-path ${{ env.ZIP_PATH }} \
            --type zip

      - name: Verify Files on Server
        run: |
          echo "Contents of /home/site/wwwroot:"
          ssh kudu@${{ env.AZURE_APP_NAME }}.scm.azurewebsites.net \
            'cd /home/site/wwwroot && ls -1'


