name: Build and deploy Node.js app to Azure Web App - dutchbrat-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Clean previous frontend and deploy folders
        run: |
          rm -rf frontend/.next
          rm -rf deploy

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build Frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend (Next.js)
        working-directory: frontend
        run: npm run build

      # Build Backend
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Build backend (TypeScript)
        working-directory: server
        run: npm run build

      # Prepare deployment package (flattened structure for Azure)
      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          mkdir -p deploy/server

          # FLATTEN frontend build and source to deploy root
          cp -r frontend/.next deploy/
          cp -r frontend/public deploy/
          cp -r frontend/app deploy/

          # Backend: build output as subdir
          cp -r server/dist deploy/server/

          # Start with frontend package.json
          cp frontend/package.json deploy/package.json

      # Merge backend dependencies into deploy/package.json (node one-liner)
      - name: Merge frontend and backend dependencies
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const frontendPkg = JSON.parse(fs.readFileSync('frontend/package.json', 'utf8'));
          const backendPkg = JSON.parse(fs.readFileSync('server/package.json', 'utf8'));
          frontendPkg.dependencies = Object.assign(
            {},
            frontendPkg.dependencies || {},
            backendPkg.dependencies || {}
          );
          fs.writeFileSync('deploy/package.json', JSON.stringify(frontendPkg, null, 2));
          EOF

      # Install production dependencies (frontend+backend) in deploy
      - name: Install production dependencies in deploy
        working-directory: deploy
        run: npm install --omit=dev

      # Debug: show what's in deploy/ before zipping
      - name: List deploy folder
        run: ls -lhR deploy

      - name: Zip deployment package
        working-directory: deploy
        run: zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: ./release.zip
