name: Build & Deploy Next.js to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NOTION_API_KEY:       ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID:         ${{ secrets.NOTION_DB_ID }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_USERNAME:     ${{ secrets.TWITTER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Create server.js for Azure
        working-directory: frontend
        run: |
          cat > server.js << 'EOF'
          const { createServer } = require('http')
          const { parse } = require('url')
          const next = require('next')
          
          const dev = process.env.NODE_ENV !== 'production'
          const hostname = 'localhost'
          const port = process.env.PORT || 3000
          
          const app = next({ dev, hostname, port })
          const handle = app.getRequestHandler()
          
          app.prepare().then(() => {
            createServer(async (req, res) => {
              try {
                const parsedUrl = parse(req.url, true)
                await handle(req, res, parsedUrl)
              } catch (err) {
                console.error('Error occurred handling', req.url, err)
                res.statusCode = 500
                res.end('internal server error')
              }
            })
            .once('error', (err) => {
              console.error(err)
              process.exit(1)
            })
            .listen(port, () => {
              console.log(`> Ready on http://${hostname}:${port}`)
            })
          })
          EOF

      - name: Update package.json for Azure
        working-directory: frontend
        run: |
          # Update package.json to use server.js
          npm pkg set scripts.start="node server.js"
          echo "Updated package.json scripts:"
          npm pkg get scripts

      - name: Zip deployment package
        working-directory: frontend
        run: zip -r ../deploy.zip . -x "*.git*" "node_modules/.cache/*"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: './deploy.zip'