name: Build and deploy Node.js app to Azure Web App - dutchbrat-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build Frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build Next.js frontend
        working-directory: frontend
        run: npm run build

      # Build Backend
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Build TypeScript backend
        working-directory: server
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r frontend/.next frontend/public frontend/next.config.js frontend/package.json frontend/staticwebapp.config.json deploy/
          cp -r server/dist server/package.json deploy/
          cp -r server/routes deploy/server/
          cp -r server/node_modules deploy/server_node_modules
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: .
