name: Build and deploy Node.js app to Azure Web App - dutchbrat-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Clean previous frontend and deploy folders
        run: |
          rm -rf frontend/.next
          rm -rf deploy

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build Frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend (Next.js)
        working-directory: frontend
        run: npm run build

      # Build Backend
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Build backend (TypeScript)
        working-directory: server
        run: npm run build

      # Prepare deployment package (flattened structure for Azure)
      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          mkdir -p deploy/server

          # Copy Next.js output and all source files
          cp -r frontend/.next deploy/
          cp -r frontend/app deploy/
          cp -r frontend/public deploy/

          # Backend: build output as subdir
          cp -r server/dist deploy/server/

          # Copy configs if present
          [ -f frontend/next.config.js ] && cp frontend/next.config.js deploy/ || true
          [ -f frontend/tsconfig.json ] && cp frontend/tsconfig.json deploy/ || true
          [ -f frontend/postcss.config.js ] && cp frontend/postcss.config.js deploy/ || true
          [ -f frontend/tailwind.config.js ] && cp frontend/tailwind.config.js deploy/ || true

          # Copy package.json/lock from backend/server
          cp server/package.json deploy/package.json
          if [ -f server/package-lock.json ]; then cp server/package-lock.json deploy/package-lock.json; fi

          # Copy .env if needed (optional)
          [ -f server/.env.production ] && cp server/.env.production deploy/server/.env.production || true
          [ -f server/.env ] && cp server/.env deploy/server/.env || true

          # Debug: list deploy dir
          ls -lhR deploy

          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Install production dependencies
        run: npm ci --omit=dev
        working-directory: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: ./
