name: Build & deploy Node.js app to Azure Web App - dutchbrat-website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean
        run: |
          rm -rf frontend/.next deploy

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 1️⃣ Build Frontend
      - name: Install frontend deps
        working-directory: frontend
        run: npm install
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # 2️⃣ Build Backend
      - name: Install server deps
        working-directory: server
        run: npm install
      - name: Build server
        working-directory: server
        run: npm run build

      # 3️⃣ Package deploy folder
      - name: Prepare deploy folder
        run: |
          mkdir -p deploy

          # Copy Next.js output, app/ and public/
          cp -r frontend/.next frontend/app frontend/public deploy/

          # Copy compiled server into deploy/dist
          mkdir -p deploy/dist
          cp -r server/dist/* deploy/dist/

          # Copy root package.json so npm start can run
          cp package.json deploy/

          # Debug: list contents
          ls -R deploy

      # 4️⃣ Upload artifact
      - name: Upload deploy folder
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download deploy artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: deploy

      - name: Debug downloaded contents
        run: ls -R deploy

      - name: Install production dependencies
        working-directory: deploy
        run: npm install --omit=dev

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: deploy
