name: Build and deploy Node.js app to Azure Web App - dutchbrat-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Clean previous frontend and deploy folders
        run: |
          rm -rf frontend/.next
          rm -rf deploy

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build Frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend (Next.js)
        working-directory: frontend
        run: npm run build

      # Build Backend
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Build backend (TypeScript)
        working-directory: server
        run: npm run build

      # Prepare deployment package
      - name: Prepare deployment package
        run: |
          mkdir -p deploy

          # Copy Next.js build output and routes/public
          cp -r frontend/.next deploy/
          cp -r frontend/app deploy/
          cp -r frontend/public deploy/
          cp frontend/next.config.js deploy/ || true

          # Copy your custom server build
          cp -r server/dist deploy/

          # Copy server package.json & lock so Azure can npm ci
          cp server/package.json server/package-lock.json deploy/ || true

          # Debug: show contents
          ls -lhR deploy

          # Zip it up
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Install production dependencies
        working-directory: .
        run: npm ci --omit=dev

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: ./
