name: Build & Deploy Next.js to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NOTION_API_KEY:       ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID:         ${{ secrets.NOTION_DB_ID }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_USERNAME:     ${{ secrets.TWITTER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Package for Azure
        # produce a ZIP of everything Azure needs
        working-directory: frontend
        run: |
          zip -r ../deploy-package.zip \
            .next \
            public \
            node_modules \
            package.json \
            next.config.js

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: 'false'
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8333198B22C94E4F8045643464BA21A2 }}
          package: './deploy-package.zip'
