name: Deploy Next.js App to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # make sure build & deploy both see your tokens
    env:
      NOTION_API_KEY:       ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID:         ${{ secrets.NOTION_DB_ID }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_USERNAME:     ${{ secrets.TWITTER_USERNAME }}
      SCM_DO_BUILD_DURING_DEPLOYMENT: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install & Build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dutchbrat-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: './frontend'



